# Generated by Django 3.2.8 on 2021-10-11 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
                ('short_text', models.TextField()),
                ('full_text', models.TextField()),
                ('tourney', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('post_date', models.CharField(max_length=50)),
                ('source', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_server.sports')),
            ],
        ),
    ]
