# Generated by Django 3.2.8 on 2021-10-14 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sports',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 16, 12, 36, 650057)),
        ),
    ]
