# Generated by Django 3.2.8 on 2021-10-16 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0002_sports_last_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='header',
            new_name='article_header',
        ),
        migrations.AlterField(
            model_name='sports',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 10, 32, 14, 758485)),
        ),
    ]
